# TCL File Generated by Component Editor 18.1
# Mon Mar 20 01:28:57 PDT 2023
# DO NOT MODIFY


# 
# camera_pix_read "camera_pix_read" v1.0
#  2023.03.20.01:28:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module camera_pix_read
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera_pix_read
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME camera_pix_read
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL img_cpu_reader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sdram_img_read_write.sv SYSTEM_VERILOG PATH ../DE1_SOC_D8M_RTL_nios_pix_xfer/DE1_SOC_D8M_RTL/image_transfer/sdram_img_read_write.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point curr_state
# 
add_interface curr_state conduit end
set_interface_property curr_state associatedClock clock
set_interface_property curr_state associatedReset ""
set_interface_property curr_state ENABLED true
set_interface_property curr_state EXPORT_OF ""
set_interface_property curr_state PORT_NAME_MAP ""
set_interface_property curr_state CMSIS_SVD_VARIABLES ""
set_interface_property curr_state SVD_ADDRESS_GROUP ""

add_interface_port curr_state curr_state curr_state Output 4


# 
# connection point img_captured
# 
add_interface img_captured conduit end
set_interface_property img_captured associatedClock clock
set_interface_property img_captured associatedReset ""
set_interface_property img_captured ENABLED true
set_interface_property img_captured EXPORT_OF ""
set_interface_property img_captured PORT_NAME_MAP ""
set_interface_property img_captured CMSIS_SVD_VARIABLES ""
set_interface_property img_captured SVD_ADDRESS_GROUP ""

add_interface_port img_captured img_captured img_captured Input 1


# 
# connection point rd2_data
# 
add_interface rd2_data conduit end
set_interface_property rd2_data associatedClock clock
set_interface_property rd2_data associatedReset ""
set_interface_property rd2_data ENABLED true
set_interface_property rd2_data EXPORT_OF ""
set_interface_property rd2_data PORT_NAME_MAP ""
set_interface_property rd2_data CMSIS_SVD_VARIABLES ""
set_interface_property rd2_data SVD_ADDRESS_GROUP ""

add_interface_port rd2_data rd2_data rd2_data Input 10


# 
# connection point rd2_req
# 
add_interface rd2_req conduit end
set_interface_property rd2_req associatedClock clock
set_interface_property rd2_req associatedReset ""
set_interface_property rd2_req ENABLED true
set_interface_property rd2_req EXPORT_OF ""
set_interface_property rd2_req PORT_NAME_MAP ""
set_interface_property rd2_req CMSIS_SVD_VARIABLES ""
set_interface_property rd2_req SVD_ADDRESS_GROUP ""

add_interface_port rd2_req rd2_req rd2_req Output 1


# 
# connection point send_img
# 
add_interface send_img conduit end
set_interface_property send_img associatedClock clock
set_interface_property send_img associatedReset ""
set_interface_property send_img ENABLED true
set_interface_property send_img EXPORT_OF ""
set_interface_property send_img PORT_NAME_MAP ""
set_interface_property send_img CMSIS_SVD_VARIABLES ""
set_interface_property send_img SVD_ADDRESS_GROUP ""

add_interface_port send_img send_img send_img Input 1


# 
# connection point rd_len
# 
add_interface rd_len conduit end
set_interface_property rd_len associatedClock clock
set_interface_property rd_len associatedReset ""
set_interface_property rd_len ENABLED true
set_interface_property rd_len EXPORT_OF ""
set_interface_property rd_len PORT_NAME_MAP ""
set_interface_property rd_len CMSIS_SVD_VARIABLES ""
set_interface_property rd_len SVD_ADDRESS_GROUP ""

add_interface_port rd_len rd_len rd_len Input 11


# 
# connection point max_addr
# 
add_interface max_addr conduit end
set_interface_property max_addr associatedClock clock
set_interface_property max_addr associatedReset ""
set_interface_property max_addr ENABLED true
set_interface_property max_addr EXPORT_OF ""
set_interface_property max_addr PORT_NAME_MAP ""
set_interface_property max_addr CMSIS_SVD_VARIABLES ""
set_interface_property max_addr SVD_ADDRESS_GROUP ""

add_interface_port max_addr max_addr max_addr Input 23


# 
# connection point start_addr
# 
add_interface start_addr conduit end
set_interface_property start_addr associatedClock clock
set_interface_property start_addr associatedReset ""
set_interface_property start_addr ENABLED true
set_interface_property start_addr EXPORT_OF ""
set_interface_property start_addr PORT_NAME_MAP ""
set_interface_property start_addr CMSIS_SVD_VARIABLES ""
set_interface_property start_addr SVD_ADDRESS_GROUP ""

add_interface_port start_addr start_addr start_addr Input 23


# 
# connection point RGB
# 
add_interface RGB conduit end
set_interface_property RGB associatedClock clock
set_interface_property RGB associatedReset ""
set_interface_property RGB ENABLED true
set_interface_property RGB EXPORT_OF ""
set_interface_property RGB PORT_NAME_MAP ""
set_interface_property RGB CMSIS_SVD_VARIABLES ""
set_interface_property RGB SVD_ADDRESS_GROUP ""

add_interface_port RGB BLUE2 blue2 Output 8
add_interface_port RGB GREEN2 green2 Output 8
add_interface_port RGB RED2 red2 Output 8


# 
# connection point img_done
# 
add_interface img_done conduit end
set_interface_property img_done associatedClock clock
set_interface_property img_done associatedReset ""
set_interface_property img_done ENABLED true
set_interface_property img_done EXPORT_OF ""
set_interface_property img_done PORT_NAME_MAP ""
set_interface_property img_done CMSIS_SVD_VARIABLES ""
set_interface_property img_done SVD_ADDRESS_GROUP ""

add_interface_port img_done img_done img_done Output 1


# 
# connection point pixel_rdy
# 
add_interface pixel_rdy conduit end
set_interface_property pixel_rdy associatedClock clock
set_interface_property pixel_rdy associatedReset ""
set_interface_property pixel_rdy ENABLED true
set_interface_property pixel_rdy EXPORT_OF ""
set_interface_property pixel_rdy PORT_NAME_MAP ""
set_interface_property pixel_rdy CMSIS_SVD_VARIABLES ""
set_interface_property pixel_rdy SVD_ADDRESS_GROUP ""

add_interface_port pixel_rdy pixel_rdy pixel_rdy Output 1


# 
# connection point wr2_data
# 
add_interface wr2_data conduit end
set_interface_property wr2_data associatedClock clock
set_interface_property wr2_data associatedReset ""
set_interface_property wr2_data ENABLED true
set_interface_property wr2_data EXPORT_OF ""
set_interface_property wr2_data PORT_NAME_MAP ""
set_interface_property wr2_data CMSIS_SVD_VARIABLES ""
set_interface_property wr2_data SVD_ADDRESS_GROUP ""

add_interface_port wr2_data wr2_data wr2_data Output 16


# 
# connection point wr2_req
# 
add_interface wr2_req conduit end
set_interface_property wr2_req associatedClock clock
set_interface_property wr2_req associatedReset ""
set_interface_property wr2_req ENABLED true
set_interface_property wr2_req EXPORT_OF ""
set_interface_property wr2_req PORT_NAME_MAP ""
set_interface_property wr2_req CMSIS_SVD_VARIABLES ""
set_interface_property wr2_req SVD_ADDRESS_GROUP ""

add_interface_port wr2_req wr2_req wr2_req Output 1

