#ifndef _ALTERA_CPU_H_
#define _ALTERA_CPU_H_

/*
* This file was automatically generated by the swinfo2header utility.
* 
* Created from SOPC Builder system 'cpu' in
* file 'D:\CPEN391\l2b-25-forks\hardware\testHPS\cpu.sopcinfo'.
*/

/*
* This file contains macros for module 'hps_0' and devices
* connected to the following masters:
*   h2f_axi_master
*   h2f_lw_axi_master
* 
* Do not include this header file and another header file created for a
* different module or master group at the same time.
* Doing so may result in duplicate macro names.
* Instead, use the system header file which has macros with unique names.
*/

/*
* Macros for device 'pixel_buffer', class 'altera_up_avalon_video_pixel_buffer_dma'
* The macros are prefixed with 'PIXEL_BUFFER_'.
* The prefix is the slave descriptor.
*/
#define PIXEL_BUFFER_COMPONENT_TYPE altera_up_avalon_video_pixel_buffer_dma
#define PIXEL_BUFFER_COMPONENT_NAME pixel_buffer
#define PIXEL_BUFFER_BASE 0x0
#define PIXEL_BUFFER_SPAN 16
#define PIXEL_BUFFER_END 0xf

/*
* Macros for device 'touchscreen_uart', class 'altera_up_avalon_rs232'
* The macros are prefixed with 'TOUCHSCREEN_UART_'.
* The prefix is the slave descriptor.
*/
#define TOUCHSCREEN_UART_COMPONENT_TYPE altera_up_avalon_rs232
#define TOUCHSCREEN_UART_COMPONENT_NAME touchscreen_uart
#define TOUCHSCREEN_UART_BASE 0x18
#define TOUCHSCREEN_UART_SPAN 8
#define TOUCHSCREEN_UART_END 0x1f
#define TOUCHSCREEN_UART_IRQ 0

/*
* Macros for device 'rgb_resampler', class 'altera_up_avalon_video_rgb_resampler'
* The macros are prefixed with 'RGB_RESAMPLER_'.
* The prefix is the slave descriptor.
*/
#define RGB_RESAMPLER_COMPONENT_TYPE altera_up_avalon_video_rgb_resampler
#define RGB_RESAMPLER_COMPONENT_NAME rgb_resampler
#define RGB_RESAMPLER_BASE 0x20
#define RGB_RESAMPLER_SPAN 4
#define RGB_RESAMPLER_END 0x23

/*
* Macros for device 'switches_pio', class 'altera_avalon_pio'
* The macros are prefixed with 'SWITCHES_PIO_'.
* The prefix is the slave descriptor.
*/
#define SWITCHES_PIO_COMPONENT_TYPE altera_avalon_pio
#define SWITCHES_PIO_COMPONENT_NAME switches_pio
#define SWITCHES_PIO_BASE 0x30
#define SWITCHES_PIO_SPAN 16
#define SWITCHES_PIO_END 0x3f
#define SWITCHES_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SWITCHES_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SWITCHES_PIO_CAPTURE 0
#define SWITCHES_PIO_DATA_WIDTH 10
#define SWITCHES_PIO_DO_TEST_BENCH_WIRING 0
#define SWITCHES_PIO_DRIVEN_SIM_VALUE 0
#define SWITCHES_PIO_EDGE_TYPE NONE
#define SWITCHES_PIO_FREQ 50000000
#define SWITCHES_PIO_HAS_IN 1
#define SWITCHES_PIO_HAS_OUT 0
#define SWITCHES_PIO_HAS_TRI 0
#define SWITCHES_PIO_IRQ_TYPE NONE
#define SWITCHES_PIO_RESET_VALUE 0

/*
* Macros for device 'buttons_pio', class 'altera_avalon_pio'
* The macros are prefixed with 'BUTTONS_PIO_'.
* The prefix is the slave descriptor.
*/
#define BUTTONS_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTONS_PIO_COMPONENT_NAME buttons_pio
#define BUTTONS_PIO_BASE 0x40
#define BUTTONS_PIO_SPAN 16
#define BUTTONS_PIO_END 0x4f
#define BUTTONS_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTONS_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTONS_PIO_CAPTURE 0
#define BUTTONS_PIO_DATA_WIDTH 4
#define BUTTONS_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTONS_PIO_DRIVEN_SIM_VALUE 0
#define BUTTONS_PIO_EDGE_TYPE NONE
#define BUTTONS_PIO_FREQ 50000000
#define BUTTONS_PIO_HAS_IN 1
#define BUTTONS_PIO_HAS_OUT 0
#define BUTTONS_PIO_HAS_TRI 0
#define BUTTONS_PIO_IRQ_TYPE NONE
#define BUTTONS_PIO_RESET_VALUE 0

/*
* Macros for device 'hexes_pio', class 'altera_avalon_pio'
* The macros are prefixed with 'HEXES_PIO_'.
* The prefix is the slave descriptor.
*/
#define HEXES_PIO_COMPONENT_TYPE altera_avalon_pio
#define HEXES_PIO_COMPONENT_NAME hexes_pio
#define HEXES_PIO_BASE 0x50
#define HEXES_PIO_SPAN 16
#define HEXES_PIO_END 0x5f
#define HEXES_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define HEXES_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEXES_PIO_CAPTURE 0
#define HEXES_PIO_DATA_WIDTH 28
#define HEXES_PIO_DO_TEST_BENCH_WIRING 0
#define HEXES_PIO_DRIVEN_SIM_VALUE 0
#define HEXES_PIO_EDGE_TYPE NONE
#define HEXES_PIO_FREQ 50000000
#define HEXES_PIO_HAS_IN 0
#define HEXES_PIO_HAS_OUT 1
#define HEXES_PIO_HAS_TRI 0
#define HEXES_PIO_IRQ_TYPE NONE
#define HEXES_PIO_RESET_VALUE 268435455

/*
* Macros for device 'sdram_controller', class 'altera_avalon_new_sdram_controller'
* The macros are prefixed with 'SDRAM_CONTROLLER_'.
* The prefix is the slave descriptor.
*/
#define SDRAM_CONTROLLER_COMPONENT_TYPE altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_COMPONENT_NAME sdram_controller
#define SDRAM_CONTROLLER_BASE 0x8000000
#define SDRAM_CONTROLLER_SPAN 67108864
#define SDRAM_CONTROLLER_END 0xbffffff
#define SDRAM_CONTROLLER_CAS_LATENCY 3
#define SDRAM_CONTROLLER_CONTENTS_INFO 
#define SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define SDRAM_CONTROLLER_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_POWERUP_DELAY 100.0
#define SDRAM_CONTROLLER_REFRESH_PERIOD 7.8125
#define SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 25
#define SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 16
#define SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_SHARED_DATA 0
#define SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_T_AC 5.4
#define SDRAM_CONTROLLER_T_MRD 3
#define SDRAM_CONTROLLER_T_RCD 15.0
#define SDRAM_CONTROLLER_T_RFC 70.0
#define SDRAM_CONTROLLER_T_RP 15.0
#define SDRAM_CONTROLLER_T_WR 14.0
#define SDRAM_CONTROLLER_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define SDRAM_CONTROLLER_MEMORY_INFO_GENERATE_DAT_SYM 1
#define SDRAM_CONTROLLER_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16


#endif /* _ALTERA_CPU_H_ */

