# TCL File Generated by Component Editor 18.1
# Wed Mar 15 12:52:07 PDT 2023
# DO NOT MODIFY


# 
# img_cpu_reader "img_cpu_reader" v1.0
#  2023.03.15.12:52:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module img_cpu_reader
# 
set_module_property DESCRIPTION ""
set_module_property NAME img_cpu_reader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME img_cpu_reader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hps_pixel_transfer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hps_pixel_transfer.sv SYSTEM_VERILOG PATH image_transfer/hps_pixel_transfer.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pix_rdy
# 
add_interface pix_rdy conduit end
set_interface_property pix_rdy associatedClock clock
set_interface_property pix_rdy associatedReset reset_sink
set_interface_property pix_rdy ENABLED true
set_interface_property pix_rdy EXPORT_OF ""
set_interface_property pix_rdy PORT_NAME_MAP ""
set_interface_property pix_rdy CMSIS_SVD_VARIABLES ""
set_interface_property pix_rdy SVD_ADDRESS_GROUP ""

add_interface_port pix_rdy pix_rdy pix_rdy Input 1


# 
# connection point pix_data
# 
add_interface pix_data conduit end
set_interface_property pix_data associatedClock clock
set_interface_property pix_data associatedReset reset_sink
set_interface_property pix_data ENABLED true
set_interface_property pix_data EXPORT_OF ""
set_interface_property pix_data PORT_NAME_MAP ""
set_interface_property pix_data CMSIS_SVD_VARIABLES ""
set_interface_property pix_data SVD_ADDRESS_GROUP ""

add_interface_port pix_data pixel_data pixel_data Input 24


# 
# connection point get_next_pix
# 
add_interface get_next_pix conduit end
set_interface_property get_next_pix associatedClock clock
set_interface_property get_next_pix associatedReset reset_sink
set_interface_property get_next_pix ENABLED true
set_interface_property get_next_pix EXPORT_OF ""
set_interface_property get_next_pix PORT_NAME_MAP ""
set_interface_property get_next_pix CMSIS_SVD_VARIABLES ""
set_interface_property get_next_pix SVD_ADDRESS_GROUP ""

add_interface_port get_next_pix get_next_pix get_next_pix Output 1


# 
# connection point img_done
# 
add_interface img_done conduit end
set_interface_property img_done associatedClock clock
set_interface_property img_done associatedReset ""
set_interface_property img_done ENABLED true
set_interface_property img_done EXPORT_OF ""
set_interface_property img_done PORT_NAME_MAP ""
set_interface_property img_done CMSIS_SVD_VARIABLES ""
set_interface_property img_done SVD_ADDRESS_GROUP ""

add_interface_port img_done img_done img_done Input 1


# 
# connection point cpu_rdy
# 
add_interface cpu_rdy conduit end
set_interface_property cpu_rdy associatedClock clock
set_interface_property cpu_rdy associatedReset ""
set_interface_property cpu_rdy ENABLED true
set_interface_property cpu_rdy EXPORT_OF ""
set_interface_property cpu_rdy PORT_NAME_MAP ""
set_interface_property cpu_rdy CMSIS_SVD_VARIABLES ""
set_interface_property cpu_rdy SVD_ADDRESS_GROUP ""

add_interface_port cpu_rdy cpu_rdy cpu_rdy Output 1


# 
# connection point pix_rdy_out
# 
add_interface pix_rdy_out conduit end
set_interface_property pix_rdy_out associatedClock clock
set_interface_property pix_rdy_out associatedReset ""
set_interface_property pix_rdy_out ENABLED true
set_interface_property pix_rdy_out EXPORT_OF ""
set_interface_property pix_rdy_out PORT_NAME_MAP ""
set_interface_property pix_rdy_out CMSIS_SVD_VARIABLES ""
set_interface_property pix_rdy_out SVD_ADDRESS_GROUP ""

add_interface_port pix_rdy_out pix_rdy_out pix_rdy_out Output 32


# 
# connection point pix_rgb_out
# 
add_interface pix_rgb_out conduit end
set_interface_property pix_rgb_out associatedClock clock
set_interface_property pix_rgb_out associatedReset ""
set_interface_property pix_rgb_out ENABLED true
set_interface_property pix_rgb_out EXPORT_OF ""
set_interface_property pix_rgb_out PORT_NAME_MAP ""
set_interface_property pix_rgb_out CMSIS_SVD_VARIABLES ""
set_interface_property pix_rgb_out SVD_ADDRESS_GROUP ""

add_interface_port pix_rgb_out pix_rgb_out pix_rgb_out Output 24


# 
# connection point out_state
# 
add_interface out_state conduit end
set_interface_property out_state associatedClock clock
set_interface_property out_state associatedReset ""
set_interface_property out_state ENABLED true
set_interface_property out_state EXPORT_OF ""
set_interface_property out_state PORT_NAME_MAP ""
set_interface_property out_state CMSIS_SVD_VARIABLES ""
set_interface_property out_state SVD_ADDRESS_GROUP ""

add_interface_port out_state out_state out_state Output 4

